services:
  vet-clinic-db:
    image: postgres:16.3-alpine
    container_name: vet-clinic-db
    ports:
      - '${DATABASE_PORT}:5432'
    volumes:
      - vet_clinic_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  vet-clinic-service:
    build: .
    container_name: vet-clinic-service
    ports:
      - '${SERVER_PORT}:8085'
    depends_on:
      vet-clinic-db:
        condition: service_healthy
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - DATABASE_URL=jdbc:postgresql://vet-clinic-db:5432/${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}

volumes:
  vet_clinic_data: